routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::get('/post','PostController@index')->name('post.index');
Route::get('/post/{slug}','PostController@show');
Route::get('/page/{slug}','PageController@show');

Route::get('/gallery/photo', 'GalleryController@indexPhoto');
Route::get('/gallery/video', 'GalleryController@indexVideo');

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Post;

class Category extends Model
{
    // relation categories
    public function posts() {
        return $this->hasMany('App\Post');
    }

    /**
	* Get all post id from active category
	*/
	public function getRelatedPostsIdAttribute()
	{
		$result = $this->posts->pluck('id')->toArray();			
		return $result;
	}

    // custom scope untuk menampilkan kategori tanpa parrent
    public function scopeNoParent($query)
	{
		return $this->where('parent_id', null);
	}

	// custom accessor untuk total post dengan kategori terkait
	public function getTotalPostsAttribute()
	{
		return Post::whereIn('id', $this->related_posts_id)->count();
	}
}

resources/views/partials/_category-panel.blade.php
<div class="widget categories">
	<header>
		<h3 class="h6">Kategori</h3>
	</header>
	@foreach(App\Category::noParent()->get() as $category)
		<div class="item d-flex justify-content-between"><a href="{{ url('/post?category=' . $category->slug) }}">{{ $category->name }}</a><span>{{ $category->total_posts or '0' }}</span></div>
	@endforeach
</div>

resources/views/partials/_disqus-comments.blade.php
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

var disqus_config = function () {
this.page.url = '{{ URL::to("/") .'/'. $post->slug }}'; 
this.page.identifier = {{ $post->slug }};; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://islamic-fashion-institute.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the 
	<a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a>
</noscript>

resources/views/partials/_latest_3-post.blade.php
<div class="row">
  @forelse (App\Post::latestPosts()->limit(3)->get() as $latpost)
    <div class="post col-md-4">
      <div class="post-thumbnail"><a href="{{ url('post',$latpost->slug) }}"><img src="{{ Voyager::image($latpost->image) }}" alt="..." class="img-fluid"></a></div>
      <div class="post-details">
        <div class="post-meta d-flex justify-content-between">
          <div class="date">{{ $latpost->created_at->format('d M | Y')}}</div>
          <div class="category"><a href="{{ url('/post?category='.$latpost->category->slug) }}">{{ $latpost->category->slug }}</a></div>
        </div><a href="post.html">
          <h3 class="h4">{{ $latpost->title }}</h3></a>
          <p class="text-muted">
            {{ str_limit($latpost->excerpt, 250 )}}
          </p>
      </div>
    </div>
  @empty
    Belum Ada Artikel
  @endforelse
</div>

resources/views/partials/_latest_post-panel.blade.php
<div class="widget latest-posts">
  <header>
    <h3 class="h6">Artikel Terbaru</h3>
  </header>
  <div class="blog-posts">
    @forelse (App\Post::latestPosts()->paginate(4) as $latpost)
      <a href="{{ url('post',$latpost->slug) }}">
        <div class="item d-flex align-items-center">
          <div class="image"><img src="{{ Voyager::image($latpost->image) }}" alt="..." class="img-fluid"></div>
          <div class="title"><strong>{{ $latpost->title }}</strong>
            <div class="d-flex align-items-center">
              <div class="views"><i class="icon-clock"></i>{{ $latpost->created_at->format('d M Y')}}</div>
              <div class="comments"><i class="icon-comment"></i><span class="disqus-comment-count" data-disqus-url="{{ URL::to("/") .'/'. $latpost->slug }}"></span></div>
            </div>
          </div>
        </div>
      </a>
    @empty
      Belum Ada Artikel
    @endforelse
  </div>
</div>

resources/views/partials/_main-menu.blade.php
<ul class="navbar-nav ml-auto">
  @foreach($items as $key => $menu_item)
    @php
        $submenu = $menu_item->children;
    @endphp
    @if(count($submenu) >= 1)
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" target="{{ $menu_item->target }}" href="{{ $menu_item->url }}" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ $menu_item->title }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            @foreach($submenu as $item)
              <a class="dropdown-item" target="{{ $item->target }}" href="{{$item->url}}">{{$item->title}}</a>
            @endforeach
        </div>
      </li>
    @else
      <li>
          <a target="{{ $menu_item->target }}" href="{{ $menu_item->link() }}" class="nav-link @if($key==0) active @endif">{{ $menu_item->title }}</a>
      </li>
    @endif
  @endforeach
</ul>